<?php

namespace SEPConseil\ArduousnessBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ard_columnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ardColumnRepository extends EntityRepository
{ 
	
}