<?php

namespace SEPConseil\ArduousnessBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\PersistentCollection;

/**
 * ard_taskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ardTaskRepository extends EntityRepository
{
	public function myFindTask()
    {
    	// liste des tâches des 3 tableaux de la vue manutention manuelle
        $qb = $this->createQueryBuilder('ardTask');

        $qb ->where('ardTask.typestask = 1');
        $qb ->where('ardTask.typestask = 2');
        $qb ->where('ardTask.typestask = 3'); 

        return $qb->getQuery()->getResult();
    }
}
