<?php

namespace SEPConseil\ArduousnessBundle\Entity;

use Doctrine\ORM\PersistentCollection;
use Doctrine\ORM\EntityRepository;

/**
 * ard_typetaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ardTypetaskRepository extends EntityRepository
{
	public function myFindTypeTask()
    {
    	//liste des 3 id de tableau de la vue manutention manuelle
        $qb = $this->createQueryBuilder('ardTypetask');

        $qb ->where('ardTypetask.id = 1');
        $qb ->where('ardTypetask.id = 2');
        $qb ->where('ardTypetask.id = 3'); 

        return $qb->getQuery()->getResult();
    }
}
