<?php

namespace SEPConseil\ArduousnessBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\PersistentCollection;
use SEPConseil\ArduousnessBundle\Entity\ardColumn;

/**
 * ard_valueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ardValueRepository extends EntityRepository
{
	public function myFindValue1()
    {
        //liste value avec l'id de tableau 1
        $qb = $this->createQueryBuilder('ardValue');

        $qb ->select('SEPConseilArduousnessBundle:ardValue.*');
        $qb ->from('ardColumn', 'SEPConseilArduousnessBundle:ardValue');
        $qb ->where('ardColumn.typestask = ardTypetask.id');
        $qb ->where('ardColumn.typestask = 1');

        return $qb->getQuery()->getResult();
    }

    public function myFindValue2()
    {
        //liste value avec l'id de tableau 2
        $qb = $this->createQueryBuilder('ardValue');

        $qb ->select('SEPConseilArduousnessBundle:ardValue.*');
        $qb ->from('SEPConseilArduousnessBundle:ardColumn', 'SEPConseilArduousnessBundle:ardValue');
        $qb ->where('ardColumn.typestask = ardTypetask.id');
        $qb ->where('ardColumn.typestask = 2');

        return $qb->getQuery()->getResult();
    }

    public function myFindValue3()
    {
        //liste value avec l'id de tableau 3
        $qb = $this->createQueryBuilder('ardValue');

        $qb ->from('SEPConseilArduousnessBundle:ardColumn');
        $qb ->where('ardColumn.typestask = ardTypetask.id');
        $qb ->where('ardColumn.typestask = 3');

        return $qb->getQuery()->getResult();
    }
}
